# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0004_venues_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
